/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 ./public/Model/SCIFI/SCIFI.gltf -r public
Author: k.loren (https://sketchfab.com/k.loren)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/scifi-landscape-db1a1578f71249fb99524073de75c02a
Title: Scifi landscape
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SCIFI(props) {
  const { nodes, materials } = useGLTF('/Model/SCIFI/SCIFI.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-6369.12, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={800}>
            <mesh geometry={nodes.Plane004_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Plane004_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[-3186.82, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={800}>
            <mesh geometry={nodes.Plane002_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Plane002_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[-12796.4, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={800}>
            <mesh geometry={nodes.Plane005_Material004_0.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Plane005_Material005_0.geometry} material={materials['Material.005']} />
          </group>
          <group position={[-9614.1, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={800}>
            <mesh geometry={nodes.Plane007_Material004_0.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Plane007_Material005_0.geometry} material={materials['Material.005']} />
          </group>
          <group position={[-7997.13, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={800}>
            <mesh geometry={nodes.Plane009_Material004_0.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Plane009_Material005_0.geometry} material={materials['Material.005']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Model/SCIFI/SCIFI.gltf')
